### ISSUE TITLE
[PE-D][Tester C] Incorrect error message displayed

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-W12-3/tp#101]
Perhaps the error message should say something else in this case?

![image.png](https://raw.githubusercontent.com/ShaniceTang/ped/main/files/ecfb6afc-0e8a-46d8-b172-fb5a3a0e6962.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: ShaniceTang/ped#2

**Comment by hooami** [comment]
Fixed in #136
