### ISSUE TITLE
[PE-D][Tester E] Duplication of given transactions 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-W12-3/tp#124]
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
![Screenshot 2023-11-03 at 8.45.08 PM.png](https://raw.githubusercontent.com/rohitcube/ped/main/files/3fc5a602-ac82-4eb2-9035-9f8d8acf35e8.png)

Since most transactions that are recurrent are unique (no one is paying for the same unique service on a subscription basis twice in the same month), maybe there could be an option to detect duplicated transactions and alert the user, or even not allow it. This feature could enhance the usability of the program and prevent mistakes from the user side.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: rohitcube/ped#12

**Comment by ChoonSiang** [comment]
Not a bug. What if the user just so happens to have 2 subscriptions for the same service? Then it should not be counted as duplicated.
