### ISSUE TITLE
[PE-D][Tester A] Missing clarification about non negative 'amount' parameter in UserGuide

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2113-W12-3/tp#99]
The UserGuide does **not specify** that the AMOUNT parameter in the 'goal /add' command has to be a positive number. In the program this condition is checked. Therefore the user guide should specify that as well

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: AlWo223/ped#4

**Comment by hooami** [comment]
Fixed in #161
